//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanwpf.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAPHANG()
        {
            this.CTNHAPs = new HashSet<CTNHAP>();
        }
    
        public string MaHD { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayHD { get; set; }
        public string MaNCC { get; set; }
        public Nullable<double> Trigia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNHAP> CTNHAPs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
